---
- name: Create users
  hosts: "*"
  tasks:
    - name: Create user for REDHAT OS FAMILY
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop:
        - recep
        - alex
        - james
        - oliver
      when: ansible_os_family == "RedHat"

    - name: Create user for SUSE OS FAMILY
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop:
        - david
        - polat
      when: ansible_os_family == "SUSE"

    - name: Create user for DEBIAN OS FAMILY
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop:
        - tomy
        - robin
      when: ansible_os_family == "Debian" or ansible_distribution_version == "20.04"