---
- name: Apache installation and configuration for ubuntuservers
  hosts: ubuntuservers
  tasks:
   - name: installing apache
     ansible.builtin.apt:
       name: apache2
       state: latest

   - name: index.html
     ansible.builtin.copy:
       content: "<h1>Hello Clarusway</h1>"
       dest: /var/www/html/index.html

   - name: restart apache2
     ansible.builtin.service:
       name: apache2
       state: restarted
       enabled: yes

- name: Apache and wget installation for webservers
  hosts: webservers
  tasks:
    - name: installing httpd and wget
      ansible.builtin.dnf:
        pkg: "{{ item }}"
        state: present
      loop:
        - httpd
        - wget
    - name: restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted
        enabled: yes